"use client";

import SkeletonWrapper from "@/components/SkeletonWrapper";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { getAnomalies, getMonthlySummary } from "@/lib/api/endpoints";
import type { AnomalyDto, AnomalySeverity } from "@/lib/api/types";
import { GetFormatterForCurrency } from "@/lib/helpers";
import { cn } from "@/lib/utils";
import { useQuery } from "@tanstack/react-query";
import { AlertTriangle, CheckCircle2, Info, OctagonAlert, TrendingDown, TrendingUp } from "lucide-react";
import Link from "next/link";
import { useMemo } from "react";

const MAX_ALERTS = 4;

const SEVERITY: Record<AnomalySeverity, { icon: typeof Info; className: string }> = {
  CRITICAL: { icon: OctagonAlert, className: "text-red-500" },
  WARNING: { icon: AlertTriangle, className: "text-amber-500" },
  INFO: { icon: Info, className: "text-blue-500" },
};

/**
 * Deterministic phrasing of the backend's anomaly facts. Numbers come straight from the analytics engine;
 * nothing here is generated by the LLM.
 */
function describe(anomaly: AnomalyDto, formatter: Intl.NumberFormat): string {
  const category = anomaly.categoryName ?? "A category";
  const pct = anomaly.deviationPercent === null ? null : Math.round(anomaly.deviationPercent);
  switch (anomaly.type) {
    case "SPENDING_SPIKE":
      return `${category} spending is ${pct}% above your 3-month average (${formatter.format(anomaly.actual)} vs ${formatter.format(anomaly.baseline)}).`;
    case "BUDGET_THRESHOLD":
      return anomaly.actual > anomaly.baseline
        ? `${category} is over budget: ${formatter.format(anomaly.actual)} spent of ${formatter.format(anomaly.baseline)}.`
        : `${category} has used ${pct}% of its ${formatter.format(anomaly.baseline)} budget.`;
    case "LARGE_TRANSACTION":
      return `A ${formatter.format(anomaly.actual)} ${category} expense is much larger than your usual ${formatter.format(anomaly.baseline)}.`;
  }
}

export function InsightsPanel({ currency }: { currency: string }) {
  const formatter = useMemo(() => GetFormatterForCurrency(currency), [currency]);

  // Keys live under "overview" so every transaction change (which invalidates ["overview"]) refreshes them.
  const summary = useQuery({ queryKey: ["overview", "insights", "summary"], queryFn: () => getMonthlySummary() });
  const anomalies = useQuery({ queryKey: ["overview", "insights", "anomalies"], queryFn: () => getAnomalies() });

  const data = summary.data;
  const forecast = data?.forecast;
  const change = data?.expenseChangePercent ?? null;

  return (
    <div className="grid gap-4 lg:grid-cols-2">
      <SkeletonWrapper isLoading={summary.isLoading}>
        <Card className="h-full">
          <CardHeader className="pb-2">
            <CardTitle className="text-base">This month so far</CardTitle>
          </CardHeader>
          <CardContent className="space-y-3 text-sm">
            {summary.isError && <p className="text-red-500">Could not load this month&apos;s summary.</p>}
            {data && (
              <>
                <Row label="Spent" value={formatter.format(data.expense)} />
                {forecast && (
                  <Row
                    label={`Projected by month end (day ${forecast.daysElapsed} of ${forecast.daysInMonth})`}
                    value={formatter.format(forecast.projectedTotal)}
                  />
                )}
                {change !== null && (
                  <Row
                    label="Compared with last month"
                    value={
                      <span className={cn("flex items-center gap-1", change > 0 ? "text-red-500" : "text-emerald-500")}>
                        {change > 0 ? <TrendingUp className="h-4 w-4" /> : <TrendingDown className="h-4 w-4" />}
                        {change > 0 ? "+" : ""}
                        {Math.round(change)}%
                      </span>
                    }
                  />
                )}
                <Row
                  label="Savings rate"
                  value={data.savingsRate === null ? "No income yet" : `${Math.round(data.savingsRate)}%`}
                />
              </>
            )}
          </CardContent>
        </Card>
      </SkeletonWrapper>

      <SkeletonWrapper isLoading={anomalies.isLoading}>
        <Card className="h-full">
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-base">Needs attention</CardTitle>
            <Link href="/budgets" className="text-xs text-muted-foreground hover:text-foreground">
              Budgets →
            </Link>
          </CardHeader>
          <CardContent className="text-sm">
            {anomalies.isError && <p className="text-red-500">Could not check for unusual spending.</p>}
            {anomalies.data?.length === 0 && (
              <p className="flex items-center gap-2 text-muted-foreground">
                <CheckCircle2 className="h-4 w-4 text-emerald-500" /> Nothing unusual this month.
              </p>
            )}
            <ul className="space-y-2">
              {anomalies.data?.slice(0, MAX_ALERTS).map((anomaly, index) => {
                const { icon: Icon, className } = SEVERITY[anomaly.severity];
                return (
                  <li key={`${anomaly.type}-${anomaly.categoryId}-${anomaly.transactionId ?? index}`} className="flex gap-2">
                    <Icon className={cn("mt-0.5 h-4 w-4 shrink-0", className)} aria-label={anomaly.severity.toLowerCase()} />
                    <span>{describe(anomaly, formatter)}</span>
                  </li>
                );
              })}
            </ul>
            {(anomalies.data?.length ?? 0) > 0 && (
              <Link
                href={`/ai?q=${encodeURIComponent("Explain the unusual spending this month and what I can do about it")}`}
                className="mt-3 inline-block text-xs font-medium text-amber-600 hover:underline dark:text-amber-400"
              >
                Ask the assistant what to do →
              </Link>
            )}
          </CardContent>
        </Card>
      </SkeletonWrapper>
    </div>
  );
}

function Row({ label, value }: { label: string; value: React.ReactNode }) {
  return (
    <div className="flex items-center justify-between gap-4">
      <span className="text-muted-foreground">{label}</span>
      <span className="font-semibold tabular-nums">{value}</span>
    </div>
  );
}
