-- liquibase formatted sql

-- changeset abhinash:create-financial-goals-1
-- Progress (remaining, months left, required monthly contribution, achieved) is derived, never stored.
CREATE TABLE financial_goals (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id        BIGINT                   NOT NULL,
  name           VARCHAR(100)             NOT NULL,
  target_amount  NUMERIC(14, 2)           NOT NULL,
  current_amount NUMERIC(14, 2) DEFAULT 0 NOT NULL,
  target_date    DATE                     NOT NULL,
  created_at     BIGINT                   NOT NULL,
  modified_at    BIGINT                   NOT NULL,
  version        INTEGER        DEFAULT 0 NOT NULL,
  CONSTRAINT financial_goals_pkey PRIMARY KEY (id),
  CONSTRAINT financial_goals_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT financial_goals_target_chk CHECK (target_amount > 0),
  CONSTRAINT financial_goals_current_chk CHECK (current_amount >= 0)
);
-- rollback DROP TABLE financial_goals;

-- changeset abhinash:create-financial-goals-idx-2
CREATE INDEX idx_financial_goals_user ON financial_goals(user_id);
-- rollback DROP INDEX idx_financial_goals_user;
