-- liquibase formatted sql

-- changeset abhinash:create-refresh-tokens-1
-- Only the SHA-256 hash of a refresh token is stored. family_id groups a login session's rotation chain,
-- so reuse of any revoked token in the chain revokes the whole family.
CREATE TABLE refresh_tokens (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id     BIGINT              NOT NULL,
  token_hash  VARCHAR(64)         NOT NULL,
  family_id   UUID                NOT NULL,
  expires_at  BIGINT              NOT NULL,
  revoked_at  BIGINT,
  user_agent  VARCHAR(255),
  created_at  BIGINT              NOT NULL,
  modified_at BIGINT              NOT NULL,
  version     INTEGER   DEFAULT 0 NOT NULL,
  CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT refresh_tokens_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
-- rollback DROP TABLE refresh_tokens;

-- changeset abhinash:create-refresh-tokens-idx-2
CREATE UNIQUE INDEX uq_refresh_tokens_token_hash ON refresh_tokens(token_hash);
CREATE INDEX idx_refresh_tokens_family_id ON refresh_tokens(family_id);
CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens(user_id);
-- rollback DROP INDEX idx_refresh_tokens_user_id; DROP INDEX idx_refresh_tokens_family_id; DROP INDEX uq_refresh_tokens_token_hash;
