-- liquibase formatted sql

-- changeset abhinash:create-budgets-1
-- A budget is a standing monthly limit for one expense category; status is computed per month on read.
CREATE TABLE budgets (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id     BIGINT              NOT NULL,
  category_id BIGINT              NOT NULL,
  amount      NUMERIC(14, 2)      NOT NULL,
  created_at  BIGINT              NOT NULL,
  modified_at BIGINT              NOT NULL,
  version     INTEGER   DEFAULT 0 NOT NULL,
  CONSTRAINT budgets_pkey PRIMARY KEY (id),
  CONSTRAINT budgets_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT budgets_category_fk FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE,
  CONSTRAINT budgets_amount_chk CHECK (amount > 0)
);
-- rollback DROP TABLE budgets;

-- changeset abhinash:create-budgets-idx-2
CREATE UNIQUE INDEX uq_budgets_user_category ON budgets(user_id, category_id);
-- rollback DROP INDEX uq_budgets_user_category;
