-- liquibase formatted sql

-- changeset abhinash:create-users-1
CREATE TABLE users (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
  email          VARCHAR(320)  NOT NULL,
  password_hash  VARCHAR(100),
  full_name      VARCHAR(120)  DEFAULT ''    NOT NULL,
  avatar_url     VARCHAR(1024),
  google_subject VARCHAR(255),
  currency       VARCHAR(3)    DEFAULT 'INR' NOT NULL,
  created_at     BIGINT                      NOT NULL,
  modified_at    BIGINT                      NOT NULL,
  version        INTEGER       DEFAULT 0     NOT NULL,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_login_method_chk CHECK (password_hash IS NOT NULL OR google_subject IS NOT NULL)
);
-- rollback DROP TABLE users;

-- changeset abhinash:create-users-idx-2
-- Emails are lower-cased in Java before every write and lookup, so a plain unique index is enough.
CREATE UNIQUE INDEX uq_users_email ON users(email);
CREATE UNIQUE INDEX uq_users_google_subject ON users(google_subject) WHERE google_subject IS NOT NULL;
-- rollback DROP INDEX uq_users_google_subject; DROP INDEX uq_users_email;
