-- liquibase formatted sql

-- changeset abhinash:create-categories-1
-- name_key is the trimmed, lower-cased name: uniqueness is case-insensitive without LOWER() in queries.
CREATE TABLE categories (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id     BIGINT              NOT NULL,
  name        VARCHAR(50)         NOT NULL,
  name_key    VARCHAR(50)         NOT NULL,
  icon        VARCHAR(16)         DEFAULT '' NOT NULL,
  type        VARCHAR(10)         NOT NULL,
  created_at  BIGINT              NOT NULL,
  modified_at BIGINT              NOT NULL,
  version     INTEGER   DEFAULT 0 NOT NULL,
  CONSTRAINT categories_pkey PRIMARY KEY (id),
  CONSTRAINT categories_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT categories_type_chk CHECK (type IN ('INCOME', 'EXPENSE'))
);
-- rollback DROP TABLE categories;

-- changeset abhinash:create-categories-idx-2
CREATE UNIQUE INDEX uq_categories_user_type_name ON categories(user_id, type, name_key);
-- rollback DROP INDEX uq_categories_user_type_name;
