-- liquibase formatted sql

-- changeset abhinash:create-insights-1
-- Proactive, template-phrased alerts produced by the daily insights job (and on demand).
-- dedupe_key identifies "the same fact" (e.g. budget-exceeded:<category>:<month>); the unique constraint makes
-- generation idempotent: re-runs, overlapping runs and retries can never create duplicates.
CREATE TABLE insights (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id     BIGINT              NOT NULL,
  type        VARCHAR(32)         NOT NULL,
  severity    VARCHAR(16)         NOT NULL,
  title       VARCHAR(120)        NOT NULL,
  body        VARCHAR(500)        NOT NULL,
  dedupe_key  VARCHAR(200)        NOT NULL,
  read_at     BIGINT,
  created_at  BIGINT              NOT NULL,
  modified_at BIGINT              NOT NULL,
  version     INTEGER   DEFAULT 0 NOT NULL,
  CONSTRAINT insights_pkey PRIMARY KEY (id),
  CONSTRAINT insights_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT insights_user_dedupe_uk UNIQUE (user_id, dedupe_key),
  CONSTRAINT insights_severity_chk CHECK (severity IN ('INFO', 'WARNING', 'CRITICAL'))
);
-- Newest-first listing per user, and the unread badge count.
CREATE INDEX idx_insights_user_recent ON insights(user_id, id DESC);
CREATE INDEX idx_insights_user_unread ON insights(user_id) WHERE read_at IS NULL;
-- rollback DROP TABLE insights;
