-- liquibase formatted sql

-- changeset abhinash:create-transactions-1
-- type is copied from the category at write time so aggregates never need a join to split income/expense.
-- category FK is RESTRICT: a category with transactions cannot be deleted.
CREATE TABLE transactions (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id          BIGINT              NOT NULL,
  category_id      BIGINT              NOT NULL,
  type             VARCHAR(10)         NOT NULL,
  amount           NUMERIC(14, 2)      NOT NULL,
  description      VARCHAR(255)        DEFAULT '' NOT NULL,
  transaction_date DATE                NOT NULL,
  created_at       BIGINT              NOT NULL,
  modified_at      BIGINT              NOT NULL,
  version          INTEGER   DEFAULT 0 NOT NULL,
  CONSTRAINT transactions_pkey PRIMARY KEY (id),
  CONSTRAINT transactions_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT transactions_category_fk FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE RESTRICT,
  CONSTRAINT transactions_type_chk CHECK (type IN ('INCOME', 'EXPENSE')),
  CONSTRAINT transactions_amount_chk CHECK (amount > 0)
);
-- rollback DROP TABLE transactions;

-- changeset abhinash:create-transactions-idx-2
CREATE INDEX idx_transactions_user_date ON transactions(user_id, transaction_date DESC);
CREATE INDEX idx_transactions_user_category ON transactions(user_id, category_id);
-- rollback DROP INDEX idx_transactions_user_category; DROP INDEX idx_transactions_user_date;
