-- liquibase formatted sql

-- changeset abhinash:create-agent-conversations-1
CREATE TABLE agent_conversations (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id         BIGINT              NOT NULL,
  title           VARCHAR(120)        NOT NULL,
  last_message_at BIGINT              NOT NULL,
  created_at      BIGINT              NOT NULL,
  modified_at     BIGINT              NOT NULL,
  version         INTEGER   DEFAULT 0 NOT NULL,
  CONSTRAINT agent_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT agent_conversations_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_agent_conversations_user_recent ON agent_conversations(user_id, last_message_at DESC);
-- rollback DROP TABLE agent_conversations;

-- changeset abhinash:create-agent-messages-2
-- Conversation memory: only the user's messages and the assistant's final replies. Tool traffic lives in
-- agent_actions, so replayed history never contains half-finished tool-call pairs.
CREATE TABLE agent_messages (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
  conversation_id BIGINT              NOT NULL,
  user_id         BIGINT              NOT NULL,
  role            VARCHAR(16)         NOT NULL,
  content         TEXT                NOT NULL,
  created_at      BIGINT              NOT NULL,
  modified_at     BIGINT              NOT NULL,
  version         INTEGER   DEFAULT 0 NOT NULL,
  CONSTRAINT agent_messages_pkey PRIMARY KEY (id),
  CONSTRAINT agent_messages_conversation_fk FOREIGN KEY (conversation_id)
    REFERENCES agent_conversations(id) ON DELETE CASCADE,
  CONSTRAINT agent_messages_role_chk CHECK (role IN ('USER', 'ASSISTANT'))
);
CREATE INDEX idx_agent_messages_conversation ON agent_messages(conversation_id, id);
-- rollback DROP TABLE agent_messages;

-- changeset abhinash:create-agent-actions-3
-- Audit of every tool call (PRD §22) and the queue of write actions awaiting user confirmation.
-- arguments/result are TEXT, not JSONB: arguments come from the LLM and may be malformed JSON, which is exactly
-- what we want to keep for debugging.
CREATE TABLE agent_actions (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id         BIGINT              NOT NULL,
  conversation_id BIGINT,
  tool_name       VARCHAR(64)         NOT NULL,
  arguments       TEXT                NOT NULL,
  result          TEXT,
  summary         VARCHAR(500),
  status          VARCHAR(24)         NOT NULL,
  latency_ms      INTEGER   DEFAULT 0 NOT NULL,
  expires_at      BIGINT,
  created_at      BIGINT              NOT NULL,
  modified_at     BIGINT              NOT NULL,
  version         INTEGER   DEFAULT 0 NOT NULL,
  CONSTRAINT agent_actions_pkey PRIMARY KEY (id),
  CONSTRAINT agent_actions_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT agent_actions_conversation_fk FOREIGN KEY (conversation_id)
    REFERENCES agent_conversations(id) ON DELETE SET NULL
);
CREATE INDEX idx_agent_actions_user_created ON agent_actions(user_id, created_at DESC);
CREATE INDEX idx_agent_actions_conversation ON agent_actions(conversation_id);
-- rollback DROP TABLE agent_actions;
